### PR TITLE
Move functions to Arm64

### PR DESCRIPTION
**Pull request by nilskelleter**
*Issue #, if available:* #184 Move functions to Arm64

*Description of changes:*
With this PR the functions of the delivery, delivery-pricing, orders, payment, platform, products, users and warehouse service are moved to Arm64.

With this PR the payment-3p service is not changed.
Also the pipeline is not changed.
Detail information in issue #184

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by nmoutschen** [comment]
Thanks a lot for this PR @nilskelleter ! I'm currently on sick leave but will review it next week.

**Comment by stefanullinger** [comment]
Hi, this sounds interesting! Can someone explain what the advantage of moving to arm64 is? Is it cheaper? Is it faster? Or can you share some link that explains it?

Thanks in advance!

**Comment by nilskelleter** [comment]
@stefanullinger

This AWS blog post is a good starting point: [https://aws.amazon.com/de/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/](https://aws.amazon.com/de/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/)

**Comment by nmoutschen** [comment]
After testing, the Python code works fine but there is an issue with the Lambda Insights extension. The current versions of the [Lambda Insights layer](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights-extension-versions.html) only support x86_64.

Since they use Go binaries, this is a blocker to merge this PR. I've contacted the PM to let them know.

**Comment by nmoutschen** [comment]
I've switch the CloudWatch Lambda Insights layer to the one that supports Arm64. All should be good now so merging this.

**Pull request merged**
